baseURL = "https://linode.com/docs/"
languageCode = "en-us"
title = "Linode Guides & Tutorials"

disableKinds = ["taxonomy", "taxonomyTerm"]

[taxonomies]
category = "categories"

[params]
description = "Guides and tutorials on the Linode platform, Linux basics, and software installation and configuration."
keywords = ["cloud hosting solutions", "linux, linux guides", "linux tutorials", "lamp guides", "lamp stack"]
default_image_width = 120
default_image_height = 120

# Date and time formatting, see https://gohugo.io/functions/format/
time_format_RFC3339 = "2006-01-02T15:04:05Z07:00"
time_format_default = "Monday, January 2, 2006"