BaseURL = "https://developers.linode.com/"
languageCode = "en-us"
title = "Developer Tools"
defaultContentLanguage = "en"
paginate = 25
preserveTaxonomyNames = true
theme = ["dlc", "linode-hugo-theme"]

# menu
[menu]

[taxonomies]
category = "categories"
tag = "tags"
language = "languages"
changelog = "changelog"

[[menu.main]]
weight = 1
name = "API Documentation"
url = "/api/v4"

[[menu.main]]
weight = 2
name = "Guides"
url = "/guides/"

[[menu.main]]
weight = 3
name = "Libraries & Tools"
url = "/libraries-tools/"

[[menu.main]]
weight = 4
name = "Changelog"
url = "/changelog/"

# params
[params]
date_format = "Monday, January 2, 2006"
copyright = "Copyright (c) 2018, Linode LLC"
logo = "/img/linode-logo_standard_light_medium.png"

[params.truncate]
enable = true

[params.topbar]
enable = true
text = "For Developers, By Developers"

[params.carousel]
enable = true

[params.features]
enable = true

[params.features2]
enable = true

[params.dev]
enable = false
