backend:
  name: git-gateway
  branch: gatsby # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "static/assets" # Media files will be stored in the repo under static/images/uploads
public_folder: "/assets" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "changelog" # Used in routes, e.g., /admin/collections/blog

    label: "Changelogs" # Used in the UI

    folder: "src/content/changelog/" # The path to the folder where the documents are stored

    create: true # Allow users to create new documents in this collection

    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md

    fields: # The fields for each document, usually in front matter
      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Publish Date"
        name: "date"
        required: true
        widget: "datetime"
        default: ""

      - label: "Changelog Type"
        name: "changelog"
        required: true
        widget: inline-select
        multiple: true
        options: ["API", "Cloud Manager"]

      - label: "Content"
        name: "body"
        widget: "markdown"
        required: true
